databases:
  - name: render_deploy
    ipAllowList: []
    plan: free
    user: render_deploy

services:
  - type: web
    plan: free
    name: render-deploy
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: render_deploy
          property: connectionString